### ISSUE TITLE
Przesunięcie błędów

### ISSUE THREAD

**Issue by mradziwo** [mradziwo/ISWiFiTesting#1]
• Jeśli ISM0-10 ma błąd E8, to ISWiFi zgłasza ("Przekroczona temperatury spalin") co jest błędęm E9
    • Jeśli ISM0-10 ma błąd E6, to ISWiFi zgłaza ("Blad czujnika temperatury spalin") co jest bledem E7

JH
to bylo na ostatniej wersji czy wczesniejszej? jesli na ostatniej, to w pliku errors.log powinien byc wpis z nr bledu i opisem, ktory takze zawiera numer (to bylo wlasnie zmenione). Inna opcja, to sterownik ISM010 wysyla co innego na modbus, a co innego pokazuje na wyswietlaczu, ale log odpowie na to pytanie 

MR 13.11.18:13:00
/ISMAll zwraca:

/ISM010_all              (200, ((16, 0), (15, 0), (14, 24), (13, 0), (12, 32767), (11, 0), (10, 0), (9, 8), (8, 0), (7, 0), (6, 0), (5, 0), (4, 0), (3, 1), (2, 20)))

Gdzie rejestr 9 zawiera informacje o błędzie – w tym przypadku błąd 8. E8 jest również wyświetlany na ISM010.

Natomiast /LastError zwraca:
	/Errors/LastError                (200, 'E9\tPrzekroczona temperatury spalin')
Wiec ISWiFi prawdłowo odczytuje numer błędu – kucha pojawia sie przy tłumaczeniu numetka na tekst

**Comment by jaroslaw-hill** [comment]
oczekiwalem, ze ISM010 zwraca liczby >= 0xE1, a zwraca po prostu koncowke numeru, sprawa rozwiazana dla E1-E9, pytanie tylko co zwroci dla bledu F1?

**Comment by mradziwo** [comment]
błąd F1 = 0d10=0x0A

**Comment by jaroslaw-hill** [comment]
Tak właśnie założyłem

śr., 14.11.2018, 20:54: Mike <notifications@github.com> napisał(a):
