### ISSUE TITLE
kasowanie plików

### ISSUE THREAD

**Issue by mradziwo** [mradziwo/ISWiFiTesting#13]
Jak wygląda w tej chwili rotacja plików logów?
W mailach z 30.01i  z 6.02 zaczęliśmy o tym rozmwaiać, ale nie wiem jaka jest końcowa implementacja. 

Jeśli istnieje wiele plików errorlog, to zapytanie GET /Errors/ErrorList zwróci mi zawartość jedynie najnowszego pliku, czy wszystkich?
Jesli w tej sytuacji wyśle zapytanie DELETE /Errors/ErrorList to skasowane zostaną wszystkie pliki?

**Comment by jaroslaw-hill** [comment]
tylko pliki z logami sa tworzone jeden na miesiac w formacie yyyy-mm.log,
pozostale sa na stale, jedynie jest do nich dopisywana kolejna informacja,
karty sa tak duze, ze nie wydaje mi sie, zeby zabraklo miejsca, wiec kasowanie mozna zrobic w czasie wizyty serwisowej lub nigdy
