### ISSUE TITLE
Czasy

### ISSUE THREAD

**Issue by mradziwo** [mradziwo/ISWiFiTesting#2]
Otrzymałem taką odpowiedź na:
200, (('/ISM010_available', 1), ('/Time/Time', 69372), ('/Time/SystemStartTime', 69181), ('/Time/SystemUptime', 191), ('/Runtime/LastIgnition', 0), ('/Runtime/StateUptime', 289),…
Jak to się mogło stać, że  '/Time/SystemUptime', wynosi 191 a  Runtime/StateUptime', 289? Jeśli wynika to z “pamiętania” przez system stanu z poprzednego uruchomienia, to powinniśmy z tej opcji zrezygnować I maksymalne czasy powinny wynosić Runtime/StateUptime

JH:
brak odczytu z rtc i zapisu wartosci poczatkowej dla StateUptime (byla wartosc 0), dla SystemUptime bylo to zrobione i przy odejmowaniu wyszlo ok, a dla StateUptime odejmowalem 0 i dlatego wyszlo wiecej niz SystemUptime, poprawione

MR 13.11.18:13:00
Niestety wciąż przy odpytaniu propertiesSettings dostałem:
/Properties/Settings             (200, (('/ISM010_available', 1), ('/Time/Time', 138018), ('/Time/SystemStartTime', 138014), ('/Time/SystemUptime', 4), ('/Runtime/LastIgnition', 0), ('/Runtime/StateUptime', 239)

gdzie system uptime jest mniejszy niż state uptime.

**Comment by jaroslaw-hill** [comment]
teraz uptime powinno byc ok, ustawialem wartosc poczatkowa w watku, ktory odpalal sie dopiero po nawiazaniu komunikacji przez wifi, teraz jest ustawiane zawsze na poczatku programu
