### ISSUE TITLE
SSID

### ISSUE THREAD

**Issue by mradziwo** [mradziwo/ISWiFiTesting#3]
Może sie zdarzyć, że dwa urządzenia będą zainstalowane w niewielkiej odległości od siebie czy możemy ustalić SSID tak samo jak “Unique ID”?

JH:
moglibysmy, ale modul ESP ma jakis problem z narzuconym SSID, mimo, ze ustawiam, to i tak ma swoje ESP_xxxx
wysylam mu "AT+CWHOSTNAME=\"ISWiFi\"\r\n" 
przy okazji, to kiedys rozmawialismy o tym, zeby zrobic zapis do Properties/Firmware, /Hardware i Id, tylko jesli jest tam domyslny nr 0 lub pusty string dla ID. Nie zrobilem tego jeszcze. Pytanie tylko, czy te wartosci maja byc przechowywane w pliku na karcie SD, czy jakos zupelnie inaczej?

MR 13.11.18:13:00
może CWSAP? 
https://room-15.github.io/blog/2015/03/26/esp8266-at-command-reference/#AT+CWSAP

**Comment by mradziwo** [comment]
JH: a co z ID? trzymamy to na karcie razem z reszta plikow?

**Comment by jaroslaw-hill** [comment]
wyslanie "AT+CWSAP=\"ISWiFi_ID\",\"password\",5,3\r\n"
dziala

**Comment by mradziwo** [comment]
dobrze, że udało się to uruchomić:)
Możemy ustawić SSID na "ISWiFi_%s", ID    
gdzie ID będzie Properties/ID

**Comment by jaroslaw-hill** [comment]
tak to wyglada
![image](https://user-images.githubusercontent.com/31095210/48484095-82ba3a00-e815-11e8-8d2a-725a5cca4b12.png)
