### ISSUE TITLE
File List

### ISSUE THREAD

**Issue by mradziwo** [mradziwo/ISWiFiTesting#4]
W odpowiedzi na    otrzymałem:
“permanent.log,,”
W sytuacji, gdy na DC znajduje się:

    Directory: E:\iswifi
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       02/01/2098     01:26            372 permanent.log
-a----       02/01/2098     01:27           8655 1970-01.log
-a----       02/01/2098     01:27            368 errors.log

JH:
czy od wywolania /FileList nie bylo zadnych operacji kasowania plikow?
a moze jeszcze nie byly utworzone pliki? ale to tylko przy wczesniejszej wersji, bo ostatnio tworze je na poczatku
musze sprawdzic, czy plik . i .. nie jest tutaj powodem dwoch przecinkow po permanent.log
c
MR 13.11.18:13:00
Sytuacja nadal taka sama: Pliki są na kardzie, nie ma operacji kasowania a /File list zwraca:
/FileList                (200, ',,permanent.log,,,')

Jakaś wskazówka moze być w ilosci przecinków przed I po permanen.log

**Comment by jaroslaw-hill** [comment]
problem jest z dlugimi nazwami, powyzej 8.3, nie rozumiem dlaczego to nie dziala, kiedys uzywalem dluzszych nazw i nie bylo problemu, w kazdym badz razie doczytalem, ze w zalozeniach projektu jest ograniczenie dlugosci na 8.3, wiec tak tez zrobilem i teraz dziala.
